language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
- pip install coverage
script:
- coverage run -m unittest
after_success:
- coverage report
before_deploy:
- openssl aes-256-cbc -K $encrypted_d7007fee4682_key -iv $encrypted_d7007fee4682_iv
  -in key.enc -out key -d
deploy:
  - provider: script
    skip_cleanup: true
    script: bash scripts/push.sh
    on:
      branch: dev
  - provider: script
    skip_cleanup: true
    script: bash scripts/deploy.sh staging
    on:
      branch: master
  - provider: script
    skip_cleanup: true
    script: bash scripts/deploy.sh release
    on:
      branch: release
